apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  namespace: webapp-yellow
  labels:
    app: nginx-app
spec:
  selector:
    matchLabels:
      app: nginx-app
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-app-john
          image: fadydevops/gke-temp:v0.4
          ports:
            - containerPort: 8080
            
