name: CI

on:
  push:
    branches:
      - main

env:
  DOCKER_REPO: fadydevops/gke-temp

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_REPO }}:${{ github.sha }}

      - name: Update deployment.yml
        run: |
           sed -i "s@image: .*/gke-temp:.*@image: ${DOCKER_REPO}:${{ github.sha }}@g" k8s/deployment.yml
          
      - name: Configure Git
        run: |
              git config --global user.email "actions@github.com"
              git config --global user.name "GitHub Actions"
              git config --global credential.helper store --file=.git/credentials
              echo "https://github.com/${{ github.repository }}" > .git/url
              echo "username=github-actions[bot]" > .git/credentials
              echo "password=${{ secrets.PAT_TOKEN }}" >> .git/credentials
          