name: Build and Push Docker Image
on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REPOSITORY: fadydevops/gke-temp

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD

      - name: Build and push Docker image
        run: |
          TAG="v0.1"
          while docker pull $DOCKER_REPOSITORY:$TAG >/dev/null 2>&1; do
            TAG=$(echo $TAG + 0.1 | bc)
          done
          docker buildx build --platform linux/amd64 --tag $DOCKER_REPOSITORY:$TAG --push .
