name: CI

on:
  push:
    branches:
      - main

env:
  DOCKER_REPO: fadydevops/gke-temp

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_REPO }}:${{ github.sha }}

      - name: Update deployment.yml
        run: |
          sed -i "s/image: fadydevops\/gke-temp:.*/image: ${DOCKER_REPO}:${{ github.sha }}/g" k8s/deployment.yml
          
      - name: Commit and push updated deployment.yml
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add k8s/deployment.yml
          git commit -m "Update deployment.yml with new image tag"
          git push
